services:

  php-dev:
    build:
      context: .
      dockerfile: images/fpm/Dockerfile
      target: dev
    volumes:
      - ./src:/var/www/html:ro
      - ./images/fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

  php-prod:
    build:
      context: .
      dockerfile: images/fpm/Dockerfile
      target: prod

  nginx-dev:
    build:
      context: .
      dockerfile: images/nginx/Dockerfile
      target: dev
    environment:
      - PHP_FPM_ADDR=php-dev:9000
      - PHP_FPM_SCRIPT_FILENAME=/var/www/html/index.php
    ports:
      - 8080:80

  nginx-prod:
    build:
      context: .
      dockerfile: images/nginx/Dockerfile
      target: dev
    environment:
      - PHP_FPM_ADDR=php-prod:9000
      - PHP_FPM_SCRIPT_FILENAME=/var/www/html/index.php
    ports:
      - 8000:80
